# required for building jre_lwjgl3glfw with Java 8 while using plugins in RealFitrexLauncher that require Java 11
# Increase Gradle daemon RAM allocation
org.gradle.jvmargs=-Xmx4096M
org.gradle.configureondemand=true

android.useAndroidX=true
android.enableJetifier=true
android.bundle.language.enableSplit=false
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false

org.gradle.jvmargs=-Xmx1g
launcher_app_name=RealFitrex Launcher
launcher_name=RealFitrex
launcher_version_code=1
launcher_version_name=1.0.0
