name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # To nam powie, jak nazywa się poprawna ścieżka (np. :app)
      - name: List projects
        run: ./gradlew projects

      # Próbujemy zbudować wszystko, co się da (bez podawania ścieżki)
      - name: Build All
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: RealFitrex-APK
          path: '**/build/outputs/apk/debug/*.apk'
