name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Wyświetlamy listę wszystkich plików, aby zobaczyć gdzie jest kod
      - name: List files
        run: ls -R
      
      # Wyświetlamy strukturę projektów
      - name: Show projects
        run: ./gradlew projects
