name: List Tasks
on: [push]
jobs:
  list-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      # Wyświetlamy dostępne zadania dla projektu :RealFitrexLauncher
      - name: List Tasks
        run: ./gradlew :RealFitrexLauncher:tasks
